version: '2'

services:

  # Core services
  audio:
    build: ./core/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - 4317:4317

  multiroom-client:
    build: ./core/multiroom/client
    restart: on-failure
